# Generated by Django 4.0.3 on 2022-06-10 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_course_name'),
        ('exam', '0008_alter_result_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='teacher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
    ]
