# Generated by Django 4.0.3 on 2022-06-10 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_remove_question_msg_id_question_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='teacher',
        ),
    ]
