# Generated by Django 4.0.3 on 2022-06-10 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_question_student_alter_question_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='student',
        ),
    ]
