# Generated by Django 4.0.3 on 2022-06-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='course_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
