# Generated by Django 4.0.3 on 2022-06-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_mis'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pass1',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='student',
            name='pass2',
            field=models.CharField(default='', max_length=70),
        ),
    ]
